// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file attestation.proto (package xyz.aspens.attestation.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file attestation.proto.
 */
export const file_attestation: GenFile = /*@__PURE__*/
  fileDesc("ChFhdHRlc3RhdGlvbi5wcm90bxIZeHl6LmFzcGVucy5hdHRlc3RhdGlvbi52MSI1ChVHZXRBdHRlc3RhdGlvblJlcXVlc3QSEgoFbm9uY2UYASABKAxIAIgBAUIICgZfbm9uY2UiVgoWR2V0QXR0ZXN0YXRpb25SZXNwb25zZRI8CgZyZXBvcnQYASABKAsyLC54eXouYXNwZW5zLmF0dGVzdGF0aW9uLnYxLkF0dGVzdGF0aW9uUmVwb3J0IlAKEUF0dGVzdGF0aW9uUmVwb3J0EhEKCXJhd19xdW90ZRgBIAEoDBISCgpjZXJ0X2NoYWluGAIgASgMEhQKDGltYWdlX2RpZ2VzdBgDIAEoDDKNAQoSQXR0ZXN0YXRpb25TZXJ2aWNlEncKDkdldEF0dGVzdGF0aW9uEjAueHl6LmFzcGVucy5hdHRlc3RhdGlvbi52MS5HZXRBdHRlc3RhdGlvblJlcXVlc3QaMS54eXouYXNwZW5zLmF0dGVzdGF0aW9uLnYxLkdldEF0dGVzdGF0aW9uUmVzcG9uc2UiAEICSAFiBnByb3RvMw");

/**
 * @generated from message xyz.aspens.attestation.v1.GetAttestationRequest
 */
export type GetAttestationRequest = Message<"xyz.aspens.attestation.v1.GetAttestationRequest"> & {
  /**
   * Caller-supplied freshness nonce (anti-replay), chosen by the verifier.
   *
   * The signer never echoes these bytes into the quote verbatim. It assembles
   * the 64-byte TDX REPORTDATA server-side as
   *
   *   REPORTDATA = SHA-512( DOMAIN || SHA256(pubkey_manifest) || SHA256(image_digests) || SHA256(nonce) )
   *
   * where `pubkey_manifest` is the canonical manifest binding ALL of the
   * signer's tx pubkeys (derived in-signer from sealed key material) and
   * `nonce` is these bytes. The quote therefore COMMITS to the nonce rather
   * than containing it: a verifier recomputes the expected REPORTDATA from
   * the nonce it chose (plus the operator-known pubkeys and image digests)
   * and requires equality against the verified quote body. A recorded quote
   * from an earlier challenge can never satisfy a fresh nonce.
   *
   * Each input is pre-hashed to 32 bytes, so the nonce has no length limit;
   * 32 random bytes is the conventional choice.
   *
   * @generated from field: optional bytes nonce = 1;
   */
  nonce?: Uint8Array;
};

/**
 * Describes the message xyz.aspens.attestation.v1.GetAttestationRequest.
 * Use `create(GetAttestationRequestSchema)` to create a new message.
 */
export const GetAttestationRequestSchema: GenMessage<GetAttestationRequest> = /*@__PURE__*/
  messageDesc(file_attestation, 0);

/**
 * @generated from message xyz.aspens.attestation.v1.GetAttestationResponse
 */
export type GetAttestationResponse = Message<"xyz.aspens.attestation.v1.GetAttestationResponse"> & {
  /**
   * @generated from field: xyz.aspens.attestation.v1.AttestationReport report = 1;
   */
  report?: AttestationReport;
};

/**
 * Describes the message xyz.aspens.attestation.v1.GetAttestationResponse.
 * Use `create(GetAttestationResponseSchema)` to create a new message.
 */
export const GetAttestationResponseSchema: GenMessage<GetAttestationResponse> = /*@__PURE__*/
  messageDesc(file_attestation, 1);

/**
 * The attestation artifact. The raw TD Quote is the ONLY authoritative
 * content: a verifier reads measurements (MRTD/RTMRs/TCB) from the
 * DCAP-verified quote body, never from self-reported fields.
 *
 * @generated from message xyz.aspens.attestation.v1.AttestationReport
 */
export type AttestationReport = Message<"xyz.aspens.attestation.v1.AttestationReport"> & {
  /**
   * Raw signed TD Quote (DCAP/QVL-verifiable): ECDSA chain to the Intel SGX
   * Root CA over the TDREPORT. Its REPORTDATA binds the signer's tx pubkeys,
   * the self-reported image digests, and the caller's nonce (see
   * GetAttestationRequest.nonce for the construction).
   *
   * @generated from field: bytes raw_quote = 1;
   */
  rawQuote: Uint8Array;

  /**
   * Optional collateral the verifier couldn't otherwise obtain (PCK chain /
   * auxblob). Usually empty -- DCAP fetches collateral from Intel PCS/PCCS and
   * the PCK chain is embedded in the quote's certification data.
   *
   * @generated from field: bytes cert_chain = 2;
   */
  certChain: Uint8Array;

  /**
   * Self-reported running image digest(s). Trust rests on the MRTD/RTMR
   * measurement policy, NOT on this self-report — a compromised signer can put
   * anything here.
   *
   * @generated from field: bytes image_digest = 3;
   */
  imageDigest: Uint8Array;
};

/**
 * Describes the message xyz.aspens.attestation.v1.AttestationReport.
 * Use `create(AttestationReportSchema)` to create a new message.
 */
export const AttestationReportSchema: GenMessage<AttestationReport> = /*@__PURE__*/
  messageDesc(file_attestation, 2);

/**
 * @generated from service xyz.aspens.attestation.v1.AttestationService
 */
export const AttestationService: GenService<{
  /**
   * @generated from rpc xyz.aspens.attestation.v1.AttestationService.GetAttestation
   */
  getAttestation: {
    methodKind: "unary";
    input: typeof GetAttestationRequestSchema;
    output: typeof GetAttestationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_attestation, 0);

